version: '3'
services:
  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
  account-service:
    build: ./account-service
    ports:
      - "23001"
    depends_on:
      - discovery-service
  customer-service:
    build: ./customer-service
    ports:
      - "23002"
    depends_on:
      - discovery-service
  gateway-service:
    build: ./gateway-service
    ports:
      - "8765:8765"
    depends_on: 
      - account-service
      - customer-service
