server:  
  port: ${PORT:8761}
    
eureka:  
  instance:
    hostname: discovery-service
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false  