server:  
  port: ${PORT:8769}
    
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/srijitm/spring-microservices
          default-label: develop
          searchPaths: configs/{application}
        native:
          search-locations: /Users/srijit/ws/java/spring-microservices/configs/{application}
      
