server:  
  port: ${PORT:8769}
    
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/srijitm/spring-microservices
          default-label: develop
          searchPaths: configs/{application}
      
eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://host.docker.internal:8761}/eureka/
    healthcheck:
      enabled: true
    fetchRegistry: true
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true
ribbon:
  eureka:
    enabled: true
  eager-load:
    enabled: true